### ISSUE TITLE
Sending eth does nothing

### ISSUE THREAD

**Issue by owen-kellie-smith** [ethers-io/EthersWallet-ios#10]
I copied an address into clipboard and app said "prepare payment?" I entered amount and password and clicked on send but no eth was sent. Am using iPhone

**Comment by ricmoo** [comment]
Heya!

To handle this in a more private channel, please cut and paste this into an e-mail to support@ethers.io.

Thanks,
RicMoo

**Comment by owen-kellie-smith** [comment]
Thanks, done but also is there a 'send eth' button or is the only way to send eth to first copy an address?

**Comment by ricmoo** [comment]
I just responded. :)

A new version coming out this week will support ENS as well. You can also send ether by scanning a QR code (either with your camera, or selecting an image from your camera roll). The camera in the lower-right corner of the screen will expose this.

Once ENS is integrated, you will be able to type in an ENS name as well.

**Comment by owen-kellie-smith** [comment]
Very cool thanks
