### ISSUE TITLE
Basic startup of library

### ISSUE THREAD

**Issue by mokn** [ethers-io/EthersWallet-ios#12]
I downloaded zip and dragged into new project. Getting linker error after adding `char *stop)` to line 44 in crypto_scrypt.h.

     duplicate symbol _crypto_scrypt in:
         /Users/mokn1/Library/Developer/Xcode/DerivedData/PocketDemo-futswqadoffnctgztwhcihqarhju/Build/Intermediates/PocketDemo.build/Debug-iphonesimulator/PocketDemo.build/Objects-normal/x86_64/crypto_scrypt-sse.o
         /Users/mokn1/Library/Developer/Xcode/DerivedData/PocketDemo-futswqadoffnctgztwhcihqarhju/Build/Intermediates/PocketDemo.build/Debug-iphonesimulator/PocketDemo.build/Objects-normal/x86_64/crypto_scrypt-ref.o
    duplicate symbol _crypto_scrypt in:
         /Users/mokn1/Library/Developer/Xcode/DerivedData/PocketDemo-futswqadoffnctgztwhcihqarhju/Build/Intermediates/PocketDemo.build/Debug-iphonesimulator/PocketDemo.build/Objects-normal/x86_64/crypto_scrypt-sse.o
         /Users/mokn1/Library/Developer/Xcode/DerivedData/PocketDemo-futswqadoffnctgztwhcihqarhju/Build/Intermediates/PocketDemo.build/Debug-iphonesimulator/PocketDemo.build/Objects-normal/x86_64/crypto_scrypt-nosse.o
     ld: 2 duplicate symbols for architecture x86_64
     clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also see that the various crypto_scrypt files are `#include` files that don't exist in the project. How can I get this up and running properly?

**Comment by ricmoo** [comment]
Are you including your own instance of the scrypt libraries? Or did you check the box to include the scrypt-ref version in the build?

**Comment by ricmoo** [comment]
If this is still an issue, please feel free to re-open the issue. Otherwise, I'm closing this.

Thanks!
