### ISSUE TITLE
How to get the private key？

### ISSUE THREAD

**Issue by chaihe** [ethers-io/EthersWallet-ios#13]
I try to use：
   
   SecureData *privateKey = [SecureData secureDataWithLength:32];

   NSString *key = [SecureData dataToHexString:[privateKey data]];

The result is：
    Printing description of key:
0x0000000000000000000000000000000000000000000000000000000000000000

so,How to get the private key？

thx

**Comment by ricmoo** [comment]
Where are you trying to get the private key from? You must specify the private key, or compute it from a mnemonic, or generate it randomly.

All that the above code does is generate the zero private key (which is invalid as a private key).

**Comment by chaihe** [comment]
thx
