### ISSUE TITLE
build tip "ethers/Address.h' file not found"

### ISSUE THREAD

**Issue by KimBin** [ethers-io/EthersWallet-ios#14]
hi,i interest in  ehter
so i  want to do something to prictise. 
thx very much

the  ehters.framework is no existent

**Comment by ricmoo** [comment]
Hey @KimBin,

To build Ethers Wallet you need two repositories from our GitHub page, in the same directory:
- EthersWallet-ios
- ethers.objc

Once you have these, open the Xcode project in EthersWallet-ios and it should build fine.

I will add these instructions to the README soon.

**Comment by ricmoo** [comment]
Let me know if this didn't work for you. Otherwise, I'm going to close this issue.
