### ISSUE TITLE
Can i use this app through my private ethers-server?

### ISSUE THREAD

**Issue by taylorshuang** [ethers-io/EthersWallet-ios#21]
I want to use this app through my private ethers-server, can you give me some advises? Can I build the eth server according to this tutorial, https://github.com/ethers-io/ethers-server. Thanks.

**Comment by ricmoo** [comment]
The ethers-server method is no longer supported, and is a remnant of a very old implementation. I should mark it deprecated.

Do you just want to connect Ethers Wallet to your own private network? If so, that is no problem. Simply modify the `- (Provider*)getProvider: (ChainId)chainId` method in `Wallet.m` to use your a JsonRpcProvider connected to your node's IP address.

In the future, I plan to expose this in the App Store version to make it easier to connect to your own node.

**Comment by taylorshuang** [comment]
Ok, thanks for your great work!
