### ISSUE TITLE
How do you get the public key

### ISSUE THREAD

**Issue by hjh1123** [ethers-io/EthersWallet-ios#23]
Hi,I want to look at the public key and test the transaction signature. Can you give me a point? Thank you very much. Happy New Year!

**Comment by ricmoo** [comment]
Happy New Year to you too!

I don't quite understand. You mean, you have a wallet which you wish to see the public key for? If so, you can extract the private key by using the mnemonic, and compute the public key from that. I recommend my [ethers.js](https://github.com/ethers-io/ethers.js) library. If you do not have the private key, but you have a transaction that was made using the wallet, you can use EC recover to determine the public key.

Does that make sense? In general, the public key is not terribly useful, so it is not easy to export.

If you use ethers.js, you can use:

```javascript
ethers.Wallet.parseTransaction(transaction);
```

**Comment by hjh1123** [comment]
yes ,thank you so much!

**Comment by hjh1123** [comment]
I see. Thank you very much.

**Comment by ricmoo** [comment]
Let me know if you have any more questions. :)
