### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by runryan** [ethers-io/EthersWallet-ios#28]
I get 'ethers/*.h' file not found error when open the project. Where can I get the ethers files?

**Comment by ricmoo** [comment]
You must install both repositories in the same directory, `ethers.objc` and `EthersWallet-iOS`. Then open the Xcode project in the `EthersWallet-iOS` folder.

See: https://github.com/ethers-io

**Comment by runryan** [comment]
Thank you so much. It works.
