### ISSUE TITLE
Ethers

### ISSUE THREAD

**Issue by Gfusss333** [ethers-io/EthersWallet-ios#56]
# Install ethers
/home/ricmoo/test-ethers> npm install ethers@beta-exports

// Import everything
import { ethers } from "ethers";

// Import just a few select items
import { BrowserProvider, parseUnits } from "ethers";

// Import from a specific export
import { HDNodeWallet } from "ethers/wallet";

<script type="module">
  import { ethers } from "https://cdnjs.cloudflare.com/ajax/libs/ethers/5.7.2/ethers.min.js";
  // Your code here...
</script>

**Comment by ricmoo** [comment]
Closing as spam.
