### ISSUE TITLE
Dnt know my password

### ISSUE THREAD

**Issue by nkululeko22** [ethers-io/EthersWallet-ios#9]
Please asist

I downloaded the ethers.io wallet to my phone, but i did not set up any passwords to it. I then bought ether amd stored it there, now i want to transfer the ethers to some one else and its asking me for password which unfortunately i do not know or have.

**Comment by ricmoo** [comment]
You cannot create a wallet in Ethers Wallet without a password, and passwords must be 6 characters or longer, maybe that will help you remember it?

If you cannot remember your password though, you can import your 12 word backup phrase to set a new password.

In the accounts page, tap the plus in the top right corner and select import. Then follow the instructions.

If you have further issues, please send an e-mail to support@ethers.io.

**Comment by ricmoo** [comment]
If you are still having issues, please let me know, otherwise, I'm closing this for now.

Thanks.
